global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'hma-local-dev'
    environment: 'development'

rule_files:
  - '/etc/prometheus/rules/*.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Scrape configurations for HMA services
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # HMA Academy Brain - Core backend
  - job_name: 'hma-academy-brain'
    static_configs:
      - targets: ['hma-academy-brain:3001']
        labels:
          service: 'academy-brain'
          tier: 'backend'
    metrics_path: '/metrics'
    scrape_interval: 30s

  # HMA Academy API Gateway
  - job_name: 'hma-academy-api'
    static_configs:
      - targets: ['hma-academy-api:3000']
        labels:
          service: 'academy-api'
          tier: 'gateway'
    metrics_path: '/metrics'
    scrape_interval: 30s

  # HMA Engine Mocks (development)
  - job_name: 'hma-engine-mocks'
    static_configs:
      - targets: ['hma-engine-mocks:4100']
        labels:
          service: 'engine-mocks'
          tier: 'compute'
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
          tier: 'database'
    scrape_interval: 30s

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          tier: 'cache'
    scrape_interval: 30s

  # MinIO metrics
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
        labels:
          service: 'minio'
          tier: 'storage'
    metrics_path: '/minio/v2/metrics/cluster'
    scheme: http
    scrape_interval: 60s

  # HMA Academy Web (frontend) - via Blackbox probe
  - job_name: 'hma-academy-web'
    metrics_path: '/probe'
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - 'http://hma-academy-web:3004/health'
        labels:
          service: 'academy-web'
          tier: 'frontend'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    scrape_interval: 30s