# HMA API Gateway Infrastructure - Kong DB-less Mode
# Simplified deployment for testing

services:
  # Kong Gateway - DB-less Mode
  kong-dbless:
    image: kong:3.4
    container_name: hma_kong_dbless
    restart: unless-stopped
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled
    volumes:
      - ./kong-dbless.yml:/kong/declarative/kong.yml:ro
    ports:
      - "8010:8000"  # Proxy (workaround for port 8000 binding issue)
      - "8001:8001"  # Admin API
    networks:
      - hma-network
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  hma-network:
    external: true
