version: "3.9"

services:
  postgres:
    image: hma/postgres:prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hma}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
      POSTGRES_DB: ${POSTGRES_DB:-hma}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-change_me}
    volumes:
      - minio:/data

volumes:
  pgdata:
  minio:
