version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "55432:5432"
    tmpfs:
      - /var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "56379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: testminio
      MINIO_ROOT_PASSWORD: testminio
    ports:
      - "59000:9000"
      - "59001:9001"
    tmpfs:
      - /data
