-- V005: Create partitioned auth.audit_log with proper PK
CREATE SCHEMA IF NOT EXISTS auth;

-- If a non-partitioned audit_log exists, migrate it
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='auth' AND c.relname='audit_log' AND c.relkind='r'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_partitioned_table p JOIN pg_class c ON c.oid=p.partrelid JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='auth' AND c.relname='audit_log'
  ) THEN
    PERFORM 1;
    EXECUTE 'ALTER TABLE auth.audit_log RENAME TO audit_log_legacy';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS auth.audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  actor_id UUID,
  action TEXT NOT NULL,
  table_name TEXT NOT NULL,
  row_id TEXT,
  before_state JSONB,
  after_state JSONB,
  PRIMARY KEY (occurred_at, id)
) PARTITION BY RANGE (occurred_at);

-- create current month partition if missing
DO $$
DECLARE
  part_name TEXT;
  start_ts TIMESTAMPTZ;
  end_ts TIMESTAMPTZ;
BEGIN
  part_name := 'audit_log_' || to_char(date_trunc('month', now()), 'YYYYMM');
  start_ts := date_trunc('month', now());
  end_ts := (date_trunc('month', now()) + INTERVAL '1 month');
  IF NOT EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relkind = 'r' AND c.relname = part_name AND n.nspname = 'auth'
  ) THEN
    EXECUTE format('CREATE TABLE auth.%I PARTITION OF auth.audit_log FOR VALUES FROM (%L) TO (%L);', part_name, start_ts, end_ts);
  END IF;
END $$;

-- migrate legacy data if present (best-effort)
INSERT INTO auth.audit_log (occurred_at, actor_id, action, table_name, row_id, before_state, after_state)
SELECT created_at, actor, action, target, NULL, metadata, NULL
FROM auth.audit_log_legacy
ON CONFLICT DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_audit_log_occurred_at ON auth.audit_log(occurred_at);

-- mark migration as applied
INSERT INTO infra.schema_migrations(version)
VALUES ('V005__auth_audit_log_partitioned.sql')
ON CONFLICT (version) DO NOTHING;
